version: '3'
services:

  web:
    image: scala3-http4s:0.1.3
    ports:
      - 8080:8080
      - 8000:8000
    environment:
      JAVA_OPTS: "-Xdebug -Xrunjdwp:server=y,transport=dt_socket,suspend=n,address=8000"
